server {
    listen 443 ssl;

    ssl_certificate /etc/nginx/ssl/ctfd.crt;
    ssl_certificate_key /etc/nginx/ssl/ctfd.key;

    location / {
        proxy_pass http://ctfd:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
